language: node_js
node_js:
- node
install:
- npm install bootstrap sass picaresque
- npx picaresque
jobs:
  include:
  - stage: Lint
    if: type = push
    script:
    - npx sass --style nested source/style.scss docassemble/jcc/abilitytopay/data/static/style.css
  - stage: Compile
    if: type = api
    script:
    - npx sass --style nested source/style.scss docassemble/jcc/abilitytopay/data/static/style.css
    - git remote add target "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
    - git add -A
    - git commit -m "ACTUALIZE ${TRAVIS_BUILD_NUMBER}"
    - git push target HEAD:$TRAVIS_BRANCH
