language: node_js
node_js:
- node
install:
- npm install bootstrap sass
jobs:
  include:
  - stage: Lint
    if: ( type = push ) && ( branch != master )
    script:
    - npx sass source/style.scss docassemble/jcc/ability-to-pay/data/static/style.css
  - stage: Release
    if: ( type = push ) && ( branch = master )
    script:
    - npx sass source/style.scss docassemble/jcc/ability-to-pay/data/static/style.css
